export default [
    { "chapter": "I", "code_range": "A00–B99", "en": "Certain infectious and parasitic diseases", "es": "Ciertas enfermedades infecciosas y parasitarias" },
    { "chapter": "II", "code_range": "C00–D48", "en": "Neoplasms", "es": "Neoplasias" },
    { "chapter": "III", "code_range": "D50–D89", "en": "Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism", "es": "Enfermedades de la sangre y de los órganos hematopoyéticos y ciertos trastornos del sistema inmunitario" },
    { "chapter": "IV", "code_range": "E00–E90", "en": "Endocrine, nutritional and metabolic diseases", "es": "Enfermedades endocrinas, nutricionales y metabólicas" },
    { "chapter": "V", "code_range": "F00–F99", "en": "Mental and behavioural disorders", "es": "Trastornos mentales y del comportamiento" },
    { "chapter": "VI", "code_range": "G00–G99", "en": "Diseases of the nervous system", "es": "Enfermedades del sistema nervioso" },
    { "chapter": "VII", "code_range": "H00–H59", "en": "Diseases of the eye and adnexa", "es": "Enfermedades del ojo y sus anexos" },
    { "chapter": "VIII", "code_range": "H60–H95", "en": "Diseases of the ear and mastoid process", "es": "Enfermedades del oído y de la apófisis mastoides" },
    { "chapter": "IX", "code_range": "I00–I99", "en": "Diseases of the circulatory system", "es": "Enfermedades del sistema circulatorio" },
    { "chapter": "X", "code_range": "J00–J99", "en": "Diseases of the respiratory system", "es": "Enfermedades del sistema respiratorio" },
    { "chapter": "XI", "code_range": "K00–K93", "en": "Diseases of the digestive system", "es": "Enfermedades del sistema digestivo" },
    { "chapter": "XII", "code_range": "L00–L99", "en": "Diseases of the skin and subcutaneous tissue", "es": "Enfermedades de la piel y del tejido subcutáneo" },
    { "chapter": "XIII", "code_range": "M00–M99", "en": "Diseases of the musculoskeletal system and connective tissue", "es": "Enfermedades del sistema osteomuscular y del tejido conjuntivo" },
    { "chapter": "XIV", "code_range": "N00–N99", "en": "Diseases of the genitourinary system", "es": "Enfermedades del sistema genitourinario" },
    { "chapter": "XV", "code_range": "O00–O99", "en": "Pregnancy, childbirth and the puerperium", "es": "Embarazo, parto y puerperio" },
    { "chapter": "XVI", "code_range": "P00–P96", "en": "Certain conditions originating in the perinatal period", "es": "Ciertas afecciones originadas en el período perinatal" },
    { "chapter": "XVII", "code_range": "Q00–Q99", "en": "Congenital malformations, deformations and chromosomal abnormalities", "es": "Malformaciones congénitas, deformidades y anomalías cromosómicas" },
    { "chapter": "XVIII", "code_range": "R00–R99", "en": "Symptoms, signs and abnormal clinical and laboratory findings, not elsewhere classified", "es": "Síntomas, signos y hallazgos anormales clínicos y de laboratorio, no clasificados en otra parte" },
    { "chapter": "XIX", "code_range": "S00–T98", "en": "Injury, poisoning and certain other consequences of external causes", "es": "Traumatismos, envenenamientos y algunas otras consecuencias de causas externas" },
    { "chapter": "XX", "code_range": "V01–Y98", "en": "External causes of morbidity and mortality", "es": "Causas externas de morbilidad y de mortalidad" },
    { "chapter": "XXI", "code_range": "Z00–Z99", "en": "Factors influencing health status and contact with health services", "es": "Factores que influyen en el estado de salud y contacto con los servicios de salud" },
    { "chapter": "XXII", "code_range": "U00–U99", "en": "Codes for special purposes", "es": "Códigos para propósitos especiales" }
]