import express from "express";
import user from "./user.js";
import category from "./category.js";
import insurance from "./insurance.js";
import role from "./role.js";
import utility from "./utility.js";
import file from "./file.js";
import permission from "./permission.js";
import privilege from "./privilege.js";
import diagnosis from "./diagnosis.js";
import event from "./event.js";
import comunication from "./comunication.js";
import procedure from "./procedure.js";
import account from "./account.js";
import speciality from "./speciality.js";
import customer from "./customer.js";
import insured from "./insured.js";
import doctor from "./doctor.js";
import policy from "./policy.js";
import provider from "./provider.js";
import contact from "./contact.js";
import conciliation from "./conciliation.js";
import ICD10 from "./ICD10.js";
import log from "./log.js";
import CPT from "./CPT.js";
import comment from "./comment.js";
import resources from "./resources.js";
import migration from "./migration.js";
import poll from "./poll.js";
import poll_answer from "./poll_answer.js";
import poll_question from "./poll_question.js";
import poll_result from "./poll_result.js";
import itinerary from "./itinerary.js";
import prescription from "./prescription.js";
import task from "./task.js";
import lodging from "./lodging.js";
import broker from "./broker.js";
import report from "./report.js";

const router = express.Router();
router.use("/user", user);
router.use("/role", role);
router.use("/category", category);
router.use("/insurance", insurance);
router.use("/file", file);
router.use("/utility", utility);
router.use("/permission", permission);
router.use("/privilege", privilege);
router.use("/diagnosis", diagnosis);
router.use("/event", event);
router.use("/comunication", comunication);
router.use("/procedure", procedure);
router.use("/account", account);
router.use("/insured", insured);
router.use("/doctor", doctor);
router.use("/contact", contact);
router.use("/policy", policy);
router.use("/provider", provider);
router.use("/speciality", speciality);
router.use("/customer", customer);
router.use("/conciliation", conciliation);
router.use("/ICD10", ICD10);
router.use("/CPT", CPT);
router.use("/log", log);
router.use("/comment", comment);
router.use("/resources", resources);
router.use("/migration", migration);
router.use("/poll", poll);
router.use("/poll-answer", poll_answer);
router.use("/poll-question", poll_question);
router.use("/poll-result", poll_result);
router.use("/itinerary", itinerary);
router.use("/prescription", prescription);
router.use("/task", task);
router.use("/lodging", lodging);
router.use("/broker", broker);
router.use("/report", report);

export default router;
